### ISSUE TITLE
Clarify the cost per GB in the documentation

### ISSUE THREAD

**Issue by shfisher** [AndrewGuenther/fck-nat#101]
The description 'fck-nat per GB: $0.00' is misleading in the context of the final AWS billing, as there is still a charge for regional traffic. It should be clarified that the $0.045/GB NAT charge is reduced to $0.01/GB for internal traffic, which provides substantial savings, though not a complete 100% reduction.
While, technically, the processing fee is 0.00$/GB, the Data Transfer costs are 0.01$/GB

**Comment by AndrewGuenther** [comment]
The docs are specifically referring to per GB processing charges for the NAT appliance. There _can_ be egress, but NAT isn't always to egress. AWS data transfer charges are a mangled web and I don't think it's sensible to try and describe the diagram below in detail.

Case in point, the charge structure you describe in the issue is also incomplete. Data egress to the internet is $0.09 per GB for the first 10TB, but you're describing cross region traffic which is a much less common use case for NATs.

I feel pretty strongly that the current wording is sufficient and it is not the responsibility of the fck-nat docs to give users a crash course on the complete data transfer pricing structure. NAT Gateways charge per GB, fck-nat does not, it's that simple.

![image](https://github.com/user-attachments/assets/9d2387fe-2e07-4beb-90b9-ac0ea6eb0b40)

**Comment by shfisher** [comment]
Appreciate your diagram.

I'm not describing the cross-region or even the cross-AZ. We see that traffic in the same region and AZ that was passing through NAT Gateway before is evaluated with fck nat as internal traffic inside the VPC and charged for 0.01/GB in Virginia.

However, while writing this, I realized that we have the ElasticIP attached to the EC2, and this operation has the same billing rate as cross-AZ traffic. ($0.010 per GB in Virginia - regional data transfer - in/out/between EC2 AZs or using elastic IPs or ELB)

Thank you for being so helpful! I appreciate it very much.
