### ISSUE TITLE
High availability mode details

### ISSUE THREAD

**Issue by AlexChesters** [AndrewGuenther/fck-nat#17]
Hi,

Apologies if this is covered in the docs (I couldn't see it anywhere). Is there any more detail about high availability mode in the CDK usage? E.g. is it an Autoscaling Group that is fixed at 1 EC2 instance? Can I configure that number at all?

**Comment by AndrewGuenther** [comment]
High availability mode is the default for CDK. And yes, it is an autoscaling group fixed at a single instance. That number is not configurable because you can only have one NAT instance routing at a time. You can only have a single IP as your default route. The intent of the autoscaling group is to ensure that a new host is brought up in the event the primary goes down.

**Comment by AlexChesters** [comment]
Ah perfect, thanks for clarifying that @AndrewGuenther 😄
