### ISSUE TITLE
Reqesting full cloudformation example connected to 'AWS::Serverless::Function' 

### ISSUE THREAD

**Issue by JamieShelley** [AndrewGuenther/fck-nat#33]
I'm sure others would benefit from an example where the FCK-NAT instance is hooked up and allows for lambda routing the greater internet.

.I have been struggling for 7+ days to get the FCK-NAT EC2 Instance working 

.I get a timeout from my lambda function being able to communicate to the outside world.
.I previously had a working cloudformation template (1 week prior) that worked with NATGateway and have been quadruple checking and fiddling with policies etc every since.

I don`t have any errors in deployment, and I'm 100% certain it's my fault in regards to malformed cloudformation.

Here is a stackoverflow post explaining my problem thus far:
https://stackoverflow.com/questions/76581555/cloudformation-natgateway-replacement-traffic-blocked-from-vpc

All the best!

**Comment by AndrewGuenther** [comment]
Based on your SO question, your issue ended up being with parts of your Cloudformation template outside of fck-nat. I can testify that the current documentation is accurate if copied correctly and a functional VPC is provided. The configuration of the VPC itself is explicitly outside the documentation which is where you seem to have run into issues. Glad you were able to get things working!

Resolving since requested documentation is out of scope.

**Comment by JamieShelley** [comment]
Thanks for the reply. It was indeed an issue with the surrounding architecture.

Perhaps a 'use cases' section could be useful to help others on your docs website? I don't mind providing my complete template as a guide.
