### ISSUE TITLE
Security Groups quota limitations

### ISSUE THREAD

**Issue by RaJiska** [AndrewGuenther/fck-nat#39]
Hi,

The documentation mentions that security groups should be used as a firewall for the EC2 hosting fck-nat, it might however cause some issue due to EC2 as reported in https://github.com/AndrewGuenther/fck-nat/issues/9#issuecomment-1780355780:

> For a NAT instance, I would recommend against using using security groups feature and allow all inbound and outbound on both IPv4 and IPv6. This is because security groups have quota limiting the number of tracked connections which can quickly be used up in a NAT scenario. More info [here](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/security-group-connection-tracking.html).

I have previously encountered this issue when experimenting with a port scanning tool, and documented it via https://github.com/robertdavidgraham/masscan/issues/365#issuecomment-1435465391,

A NAT instance would probably be very exposed to this problem, therefore requiring to manage this issue via `iptables`, where kernel configuration can be fine tuned to support more active connections.

**Comment by AndrewGuenther** [comment]
I think that it would be good to provide this as an option rather than a default. Security groups are well understood and integrate with a ton of other existing tooling so I think that's still the correct default recommendation. I think those connection limits are good enough for most people, but allowing users to enable iptables enforcement as well as supporting documentation that users should monitor their `conntrack_allowance_exceeded` and `conntrack_allowance_available` metrics.
