### ISSUE TITLE
What are the supported instance types?

### ISSUE THREAD

**Issue by RohanDey02** [AndrewGuenther/fck-nat#56]
Are we limited to the t4g series, or can we use other EC2 instances such as t3, t2, etc? This is just out of my curiosity. @AndrewGuenther

**Comment by AndrewGuenther** [comment]
Yes, the fck-nat AMI is available in both ARM and x86 so you can use whatever instance type you want.

**Comment by moltar** [comment]
Hm, I tried today with `T3A`, and it failed to deploy with this error message:

> Group did not stabilize. Last scaling activity: The architecture 'x86_64' of the specified instance type does not match the architecture 'arm64' of the specified AMI. Specify an instance type and an AMI that have matching architectures, and try again.

**Comment by RohanDey02** [comment]
@moltar It looks like you're still using the ARM64 AMI. t3a supports x86_64, so you'll need to use the x86_64 AMI (can find it in the EC2 AMI Locator).

**Comment by moltar** [comment]
Oh, I see. I was assuming it'd just pick the right AMI for me based on the instance knowledge.

**Comment by florian-klemt** [comment]
I also just ran into this issue using the cdk code. Without further configuration it seems to be set to using the ARM AMI by default. This would be nice to mention in the documentation (or remove the t3.micro recommendation from the docs)

**Comment by AndrewGuenther** [comment]
t3.micro works just fine, you just need to use the appropriate platform AMI. We've got docs on how to get the list of available images, but I can add an example closer in-line with the CDK and Terraform examples.

**Comment by florian-klemt** [comment]
What was confusing from my side is that it was nowhere mentioned that there is a configuration difference between arm and x64 and I also didn't know by heart which instance is arm and which is x64. 
Suggestion would be to show (cdk) configuration for both arm and x64 and also add a column to the recommended instances specifying if arm or x64.

But thanks for the great work. I was so annoyed by the high NAT costs, especially when I have a super cost effective setup otherwise with everything running on Lambda.
