### ISSUE TITLE
nftables vs iptables

### ISSUE THREAD

**Issue by unquietwiki** [AndrewGuenther/fck-nat#68]
I noticed looking at the code, that this was leveraging some basic iptables rules. I'm not sure if you're using an iptables that bridges to nftables, but you might have better support and speed by using nftables to write the rules. Might be overkill for this too; just a thought. Thanks!

- https://netfilter.org/projects/nftables/index.html
- https://wiki.nftables.org/wiki-nftables/index.php/Main_Page

**Comment by AndrewGuenther** [comment]
As far as I'm aware, Amazon Linux 2023 `iptables` translated `nftables` under the hood. I don't see a strong reason to explicitly migrate from one to the other at this point in time. I'll consider making the switch in the 2.0 release since the rules are going to get a bit more complicated there and we might get some benefit from the brevity of `nftables`, but I'm going to close out this particular issue since I wouldn't consider that change explicitly "planned".

**Comment by unquietwiki** [comment]
Cool beans. Thanks for considering this!
