### ISSUE TITLE
Enabling GitHub's "Discussions" feature

### ISSUE THREAD

**Issue by alexanderankin** [AndrewGuenther/fck-nat#78]
Hi Andrew and contributors,

Would you consider enabling GitHub discussions?

Thank you!

**Comment by AndrewGuenther** [comment]
Hey @alexanderankin, any particular reason why? For small projects like this one, I prefer to keep everything inside of issues because it's doesn't introduce much noise and keeps everything in one place.

**Comment by alexanderankin** [comment]
sure - i am generally anxious about trying to fit my scattered thoughts into a structure, in this case i'm not really qualified to help out with this project (at least this is my first impression) but i do kind of which there was a "back of the classroom" where i could hang out and still exchange ideas.

for example - i tried out the terraform module for this project and was not able to make it work. I then looked at the source code in here and was able to put together a very simple user data script for an ubuntu ami - perhaps amazon linux is slightly different. obviously this is not the direction of the project, as youre implementing on amazon linux. however, im sure there are others who would rather make it work on ubuntu, or some other combination of circumstances, or whatever...

also - i wanted to make some kind of a post to improve the SEO of the docs page to use the RPM or whatever, as i imagined those AMIs may not be there forever and incur costs, but a source code package or .DEB/.RPM may be something operationally a lot more feasible.

additionally, i wasted almost half a day today learning about nat64, rather, trying not learn about it - i was hoping to get a public ipv6 on aws (impossible?) and do a NAT setup where i was able to talk to public ipv4's without having to pay AWS $4/mo for this myself (impossible.). So maybe part of the good that this project brings into the world is simply aggregating people interested in this stuff? and then i dont want to make an issue claiming there is something wrong with fck-nat, just want to read up on the conversations.

**Comment by AndrewGuenther** [comment]
> im sure there are others who would rather make it work on ubuntu, or some other combination of circumstances, or whatever...

We can open an interest check for this, but I'd be very curious why Ubuntu in particular is desirable for this use case. I have suspicions, but would like to hear from users.

> also - i wanted to make some kind of a post to improve the SEO of the docs page to use the RPM or whatever, as i imagined those AMIs may not be there forever and incur costs, but a source code package or .DEB/.RPM may be something operationally a lot more feasible.

Not quite sure what you're looking for here? The AMIs aren't going anywhere. Are you asking for the docs to make it more clear that an RPM package is available as an alternate install method?

> So maybe part of the good that this project brings into the world is simply aggregating people interested in this stuff?

Part of my hesitation to turn on discussions is simply: I don't want to operate a community for this. Not that I don't think it would be valuable, but I simply do not have the time to be responsible for it. There are plenty of networking and AWS focused communities around and I don't think this project needs to add to that.

> i dont want to make an issue claiming there is something wrong with fck-nat, just want to read up on the conversations. and educate myself from the best.

It's unfortunate that these are called "issues" because that really gives the wrong impression. Most discussions can happen inside of issues. Support, feature requests, bugs, etc, can all work fine inside of issues and they're generally easier for me to manage as a solo maintainer.

**Comment by alexanderankin** [comment]
totally understood, I feel the same way from the maintainers perspective - e.g. testcontainers/testcontainers-python#517

> I don't want to operate a community for this

✔️
