### ISSUE TITLE
disable ssh?

### ISSUE THREAD

**Issue by plarsson** [AndrewGuenther/fck-nat#9]
Is it possible to disable ssh or make it optional?   Would be nice to have a stealth instance for portscanning.

**Comment by AndrewGuenther** [comment]
You can disable the sshd service using `UserData` when you launch the AMI[1]. Also, make sure your security groups are only allowing inbound traffic coming from within your VPC.

[1]: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/user-data.html

**Comment by RaJiska** [comment]
Hi @AndrewGuenther ,

> You can disable the sshd service using `UserData` when you launch the AMI[1](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/user-data.html).

Interestingly enough `systemctl disable sshd` doesn't seem to work and SSH will start regardless on reboot. TO fix the issue I had to use `systemctl mask sshd`.

> Also, make sure your security groups are only allowing inbound traffic coming from within your VPC.

For a NAT instance, I would recommend against using using security groups feature and allow all inbound and outbound on both IPv4 and IPv6. This is because security groups have quota limiting the number of tracked connections which can quickly be used up in a NAT scenario. More info [here](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/security-group-connection-tracking.html).

As an alternative, one might use `iptables` directly within the instance to block inbound connections. The conntrack table should probably be tuned as well with an increased max connections (more RAM usage), and lower timeouts.
